/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as GamingRouteImport } from './routes/gaming'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as ExploreIndexRouteImport } from './routes/explore.index'
import { Route as ExploreSlugRouteImport } from './routes/explore.$slug'
import { Route as HardwareIndexRouteImport } from './routes/hardware.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingRoute = GamingRouteImport.update({
  id: '/gaming',
  path: '/gaming',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreSlugRoute = ExploreSlugRouteImport.update({
  id: '/explore/$slug',
  path: '/explore/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareIndexRoute = HardwareIndexRouteImport.update({
  id: '/hardware/',
  path: '/hardware/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/gaming': typeof GamingRoute
  '/trending': typeof TrendingRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/explore/': typeof ExploreIndexRoute
  '/hardware/': typeof HardwareIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/gaming': typeof GamingRoute
  '/trending': typeof TrendingRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/explore': typeof ExploreIndexRoute
  '/hardware': typeof HardwareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/compare': typeof CompareRoute
  '/gaming': typeof GamingRoute
  '/trending': typeof TrendingRoute
  '/explore/$slug': typeof ExploreSlugRoute
  '/explore/': typeof ExploreIndexRoute
  '/hardware/': typeof HardwareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/compare'
    | '/gaming'
    | '/trending'
    | '/explore/$slug'
    | '/explore/'
    | '/hardware/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/compare'
    | '/gaming'
    | '/trending'
    | '/explore/$slug'
    | '/explore'
    | '/hardware'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/compare'
    | '/gaming'
    | '/trending'
    | '/explore/$slug'
    | '/explore/'
    | '/hardware/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CompareRoute: typeof CompareRoute
  GamingRoute: typeof GamingRoute
  TrendingRoute: typeof TrendingRoute
  ExploreSlugRoute: typeof ExploreSlugRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  HardwareIndexRoute: typeof HardwareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming': {
      id: '/gaming'
      path: '/gaming'
      fullPath: '/gaming'
      preLoaderRoute: typeof GamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$slug': {
      id: '/explore/$slug'
      path: '/explore/$slug'
      fullPath: '/explore/$slug'
      preLoaderRoute: typeof ExploreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware/': {
      id: '/hardware/'
      path: '/hardware'
      fullPath: '/hardware/'
      preLoaderRoute: typeof HardwareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CompareRoute: CompareRoute,
  GamingRoute: GamingRoute,
  TrendingRoute: TrendingRoute,
  ExploreSlugRoute: ExploreSlugRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  HardwareIndexRoute: HardwareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
